### ISSUE TITLE
Issue with installing xcode

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#101]
The last two times I tried to install Xcode via `xcode-select --install` in the terminal (as our install instructions suggest) I have gotten this error:

<img width="508" alt="Screen Shot 2020-10-23 at 10 09 45 PM" src="https://user-images.githubusercontent.com/6865016/97068467-ab5c1a00-157c-11eb-80de-f4bc598bd9df.png">

The solution is to install via https://developer.apple.com/download/more/

<img width="1031" alt="Screen Shot 2020-10-23 at 10 13 29 PM" src="https://user-images.githubusercontent.com/6865016/97068521-0c83ed80-157d-11eb-8e75-2e05924ae0f5.png">

Tagging @jennybc in case she has any insight.

**Comment by jennybc** [comment]
This is the first I've heard of this.

**Comment by joelostblom** [comment]
@armanawn How was the xcode installation for you this year?

**Comment by armansa1** [comment]
> @armanawn How was the xcode installation for you this year?

I didn't experience any problems installing xcode on my machine.

**Comment by jennybc** [comment]
I recently did a clean Big Sur install and I don't remember this causing any trouble.

**Comment by joelostblom** [comment]
Thanks both, closing.
