### ISSUE TITLE
Jupyter extension to install built-in R pipe

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#110]
@joelostblom @flor14 @armanawn - I have opened this PR to suggest to Ryan Homer that he update his Jupyter extension from using the tidyverse pipe in R, to using the new built-in pipe: https://github.com/techrah/jupyterext-text-shortcuts/pull/16 

If he takes my suggestion, then let's continue using his version of the extension. If not we can instead use a extension I built off of forking his code:  https://www.npmjs.com/package/@ttimbers/text-shortcuts

**Comment by ttimbers** [comment]
Ryan just accepted the PR to update his package to the built-in pipe, feel free to keep using `@techrah/jupyterext-text-shortcuts` in the install instructions as it is.

**Comment by flor14** [comment]
Great, I have re-installed it, and works fine.
For the shortcuts to match between Jupyter Lab and RStudio, students should change one of the RStudio configuration options. I will also include this change in the installation instructions.

![image](https://user-images.githubusercontent.com/29610858/126806892-16b631e5-faf8-4dd2-92c4-182d22feb8ba.png)

**Comment by ttimbers** [comment]
Great, agree this should be part of our installation instructions!
