### ISSUE TITLE
Bash not installed on some M1 macs?

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/UBC-MDS.github.io-jekyll#121]
Two students mentioned that bash was not installed on their M1 macs and they needed to install it via homebrew. I could not find confirmation of that some versions of M1 mac exclude bash. Installing via homebrew gives a later version than what we check for in he script on mac (5 instead of 3). There should not be any issues for these students other than the setup script failing. Ideally these issues would be solved by moving to zsh when wsl2 is ready on windows (#72).

**Comment by armansa1** [comment]
This is strange, I don't remember that I needed to install bash separately on my M1 Mac...

**Comment by joelostblom** [comment]
Yes and there are several other students with M1s and no issues. Sounds really weird that it wouldn't be there by default, but apple are not exactly known to shy away from breaking changes so I wouldn't be surprised either =)

**Comment by flor14** [comment]
I installed it in a Mac M2 without problems

**Comment by flor14** [comment]
If students want to install with homebrew because they want Bash 5.1 I think it should be fine because on Windows and Linux we are using Bash 5.1. I would answer that it is up to them. Comments? @joelostblom

**Comment by joelostblom** [comment]
Yes I agree, if  they are comfortable with using homebrew it seems like it is fine for them to update their bash. The same if some students are OK using Zsh on their own and modifying the setup. I usually tell students that do any modifications to our setup that this means we cannot guarantee that we can help them and they might lose time troubleshooting on their own, and that they must mention that they modified the setup whenever they ask for help that is computer related so that the instructor helping them is aware.
