### ISSUE TITLE
Double check that miniconda has released a Python 3.10 installer before the program starts in fall 2022

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/UBC-MDS.github.io-jekyll#133]
Requested here https://github.com/conda/conda-docs/issues/775

**Comment by flor14** [comment]
This is not going to be on time as we already discussed it @joelostblom . Should we close this issue? It was helpful to include the installation of python 3.10

**Comment by joelostblom** [comment]
Yup, I can add it later whenever they reply to my issue instead.
