### ISSUE TITLE
Remove or replace Jupyter-LSP for next year

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/UBC-MDS.github.io-jekyll#134]
I still think JupyterLSP provides the best linting info for JupyterLab, but it has some unfortunate issues where it takes up full CPU, hides code cells, or just doesn't work. I think the tab completion in JupyterLab is becoming good enough so that we don't need LSP for that, and most of the outstanding issues relate to linting.

An alternative for linting is jupyterlab-flake8, but there is an outstanding widespread issue (https://github.com/mlshapiro/jupyterlab-flake8/issues/37) that hasn't been fixed for two years and makes it unusable without significant tweaking. Then there is jupyterlab_code_formatter (with autopep8) which works the best of the options, but does not provide highlighting of the code, it just reformats it. I think this is not as ideal because we want students to realize the errors they are making both in their code style but also have undefined variables underlined, etc (this is useful both in VS Code and R Studio). I don't think the automatic reformatting of black or yapf (in jupyterlab_code_formatter) are working that great, so I would vote not to use these by default since they would likely require some of config to do well.

It seems a bit to me that we are back to no linter from the start of the program, and showing jupyterlab_code_formatter as an optional addon in 511. I guess another point for notebooks in VS Code for now since it comes for free there. CC @armanawn since we talked a bit about this today.

**Comment by joelostblom** [comment]
I just noticed that JupyterLab is working on directly integrating LSP services (https://github.com/jupyterlab/jupyterlab/pull/12899 and the PR it references). They will be based on jupyter-lsp extension, but hopefully not have the same issues if they are integrated into the core of jupyterlab. So we could wait for that to happen and not use anything for next year.

**Comment by flor14** [comment]
Sounds good! Thanks for sharing your thoughts about this 💯
