### ISSUE TITLE
Recommend setting the mama solver as the default now that it is no longer experimental

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/UBC-MDS.github.io-jekyll#164]
This brings significant speed ups, it would be great if as many MDS instructors as possible to change to this config and try it out before recommending this change in the installation instructions (although it should be fine) https://www.anaconda.com/blog/a-faster-conda-for-a-growing-community

**Comment by joelostblom** [comment]
I have been running this and it has been working well for me. Did anyone else have a chance to try this out?

cc @chendaniely for including this in the installation instructions this year.

**Comment by ttimbers** [comment]
I love the typo (I think its one) of "mama" solver in the title of this issue ❤️ .  I love it because I think of myself as a "mama solver" (a mama who solves problems 😂

In more seriousness this should be "mamba" right?

**Comment by joelostblom** [comment]
Haha, I will keep the typo because I like it too =) And yes, it should say "mamba". To try it out, you can do:

```
conda install -n base conda-libmamba-solver
conda config --set solver libmamba
```
