### ISSUE TITLE
"OK" missing in check-setup-mds.sh script for RStudio on Windows

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#187]
Reporting here the missing "OK" from the check script on Windows for RStudio (example pasted below for convenience) initially reported by @chendaniely 

What is reports for RStudio on Windows:

```
## System programs
OK        psql (PostgreSQL) 15.4
 2023.06.2+561dio
OK        tlmgr revision 66798 (2023-04-08 02:15:21 +0200)
```

What it should report: 

```
## System programs
OK        psql (PostgreSQL) 15.4
OK        2023.06.2+561dio
OK        tlmgr revision 66798 (2023-04-08 02:15:21 +0200)
```

**Comment by joelostblom** [comment]
Hmmm, I can't see what is going on here either from just looking at the output and the script. I am unsure when I can get to this and it would be the easiest to troubleshoot on a windows machine, so feel free to suggest a solution if you have the time to play around with it on your machine @chendaniely . But as you said, I don't think this is critical if we don't get to it. Quite mysterious though... I wonder where that `"OK"` went....

**Comment by joelostblom** [comment]
@andytai7 @chendaniely Do you still see this when running through the script this year? If so, we can try to find a fix, otherwise we can resolve this issue.

**Comment by joelostblom** [comment]
Working this year
