### ISSUE TITLE
Installing R from somewhere other than CRAN

### ISSUE THREAD

**Issue by jennybc** [UBC-MDS/UBC-MDS.github.io-jekyll#20]
Re: the setup instructions.

The content developing in "What They Forgot ..." might be interesting for this crew to track / be aware of.

For example, these sections describe the downsides of installing R with conda or homebrew vs. using a binary built by CRAN and the usual package installation workflow:

https://whattheyforgot.org/setup-an-r-dev-environment.html#what-about-conda

https://whattheyforgot.org/setup-an-r-dev-environment.html#what-about-homebrew

**Comment by ttimbers** [comment]
I think these are great resources for Platforms. Opened an issue in the instructors repo there.
