### ISSUE TITLE
Updating the Windows Installation Guide

### ISSUE THREAD

**Issue by andytai7** [UBC-MDS/UBC-MDS.github.io-jekyll#216]
### Git, Bash, and Windows Terminal

Abruptly stops after setting the default branch name to "main" for git setup. If everything else is default, inform students that it is before moving on to Windows Terminal setup.

### RStudio

Instruct students to type in the start menu “Edit the system environment variables”, instead of typing “env”.

### Jupyter Lab Shortcuts

Same keyboard shortcut changes as Ubuntu. Maybe include a screenshot of what the saved settings should look like and elaborate that all the old JSON should be underneath the new settings for the default shortcuts. Is this something we want for students?

### LaTeX

It seems like the `ms` package doesn't exist for Jupyter, as an error occurs when inputting:
```bash
tlmgr install ms
```
Should add that if the above command fails, try installing a few packages at a time instead of all of them at once.

**Comment by andytai7** [comment]
Everything else seems to work great! Please let me know if i can make these changes: @joelostblom @chendaniely, and i can make a pull request.

**Comment by joelostblom** [comment]
> Git, Bash, and Windows Terminal

I don't know enough about the process on Windows to test this. I'll leave it up to you two to decide what you prefer

> RStudio

I don't have a strong opinion here

> Jupyter Lab Shortcuts & Latex

Same comments as I made on #215

**Comment by andytai7** [comment]
>I don't have a strong opinion here

I've made the change so that it's a bit less confusing. 

>Same comments as I made on https://github.com/UBC-MDS/UBC-MDS.github.io/issues/215

That was a typo. The MS package for tlmgr is either depreciated or does not exist anymore. With testing it seems like everything LaTeX works without it, so I suggest taking it out.

**Comment by chendaniely** [comment]
closing since this seems to be fixed in  #217
