### ISSUE TITLE
Update installation script for 2024/25

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/UBC-MDS.github.io-jekyll#218]
@chendaniely @andytai7 I'm happy to help update the script as in previous years, but I don't have access/time to do the full installation from scratch so since you are doing this already, please let me know if anything is not marked `OK` when you run the script check in the bottom of the installation notes for each OS. There are usually several packages marked as missing each year when new versions come out and in addition to that there might be some packages where we want to restrict the lower version further?

**Comment by andytai7** [comment]
The one script that gave me an error for Ubuntu and Windows so far has been when i've used the `tlmgr` TeX Live package manager to install the LaTeX package `ms`. That has caused an error, so i suggest taking that package out?

**Comment by joelostblom** [comment]
Yes, we will take that out, but I was referring to this section https://ubc-mds.github.io/resources_pages/install_ds_stack_ubuntu/#post-installation-notes. Were you able to run that bash script and have everything marked OK?

**Comment by andytai7** [comment]
For Ubuntu, this is what i have but you can clealry see below that rstudio, psql, and docker are all installed on the ubuntu machine.

In addition Rmarkdown and LaTeX are installed so i'm not sure what's up with the rmarkdown PDF and HTML generation:

## Operating system
Operating System: Ubuntu 24.04 LTS
Architecture:     x86-64
Kernel:           Linux 6.8.0-39-generic

MISSING You are recommended to use Ubuntu 22.04.

## System programs
MISSING   psql=14.*
MISSING   rstudio=2023.06.*
OK        R 4.4.1 (2024-06-14) -- "Race for Your Life"
OK        python 3.12.2
OK        conda 4.7.1
OK        bash 5.2.21(1)-release (x86_64-pc-linux-gnu)
OK        git 2.43.0
OK        make 4.3
OK        latex 3.141592653-2.6-1.40.26 (TeX Live 2024)
OK        tlmgr 5-24 09:30:36 +0200)
MISSING   docker=24.*
OK        code 1.92.1

## Python packages
OK        otter-grader=5.5.0
OK        pandas=2.2.2
OK        nbconvert-core=7.16.4
OK        playwright=1.45.1
OK        jupyterlab=4.2.4
OK        jupyterlab-git=0.50.1
OK        jupyterlab-spellchecker=0.8.4
OK        jupyterlab PDF-generation was successful.
OK        jupyterlab WebPDF-generation was successful.
OK        jupyterlab HTML-generation was successful.

## R packages
OK        tidyverse=2.0.0
OK        markdown=1.13
OK        rmarkdown=2.27
OK        renv=1.0.7
OK        IRkernel=1.3.2
OK        tinytex=0.52
OK        janitor=2.2.0
OK        gapminder=1.0.0
OK        readxl=1.4.3
OK        ottr=1.1.3
OK        canlang=0.0.1
MISSING   rmarkdown PDF-generation failed. Check that latex and rmarkdown are marked OK above.
MISSING   rmarkdown HTML-generation failed. Check that rmarkdown is marked OK above.


![453371430_349443008233189_7766099893233257695_n](https://github.com/user-attachments/assets/9d7c2e22-cb3b-4ce4-a543-82375aacb4e2)

![453709384_1563909937811601_4215905786649977026_n](https://github.com/user-attachments/assets/6a409fe9-b62e-4e37-b785-e18acd365c2e)

![453175293_1215421426460075_7351046746001008517_n](https://github.com/user-attachments/assets/f26c6b5a-46cd-43bc-88e1-de2c9bc1e439)

**Comment by andytai7** [comment]
For the windows check, i think this is something i missed, it looks very different between Ubuntu and Windows, and i think Windows Post-installation notes instructions needs to be edited. What do you think @joelostblom ?

**Comment by andytai7** [comment]
For windows this is what i have, again problems with PSQL, Rstudio, and Docker but they are all installed. Also on windows, there seems to be a problem with checking that Chromium is installed but you can see in the screenshot that it works fine from jupyter lab. 

I tried running this again but it was all installed already: 
`pip install "nbconvert[webpdf]" playwright install chromium`

```
## Operating system
Microsoft Windows 11 Pro
64-bit
10.0.22621

MISSING You need Windows 10 or 11 with build number >= 10.0.19041. Please run Windows update.

## System programs
MISSING   psql 15.*
MISSING   rstudio 2023.06*
OK        tlmgr revision 71331 (2024-05-24 09:30:36 +0200)
OK        R 4.4.1 (2024-06-14 ucrt) -- "Race for Your Life"
OK        python 3.12.3
OK        conda 4.7.1
OK        bash 4-pc-msys)
OK        git 2.46.0.windows.1
OK        make 4.4.1
OK        latex 3.141592653-2.6-1.40.26 (TeX Live 2024)
MISSING   docker=24.*
OK        code 1.91.1

## Python packages
OK        otter-grader=5.5.0
OK        pandas=2.2.2
OK        nbconvert-core=7.16.4
OK        playwright=1.45.1
OK        jupyterlab=4.2.4
OK        jupyterlab-git=0.50.1
OK        jupyterlab-spellchecker=0.8.4
OK        jupyterlab PDF-generation was successful.
MISSING   jupyterlab WebPDF-generation failed. It seems like you have not run playwright install chromium to download chromium for jupyterlab WebPDF export.
OK        jupyterlab HTML-generation was successful.

## R packages
OK        tidyverse=2.0.0
OK        markdown=1.13
OK        rmarkdown=2.27
OK        renv=1.0.7
OK        IRkernel=1.3.2
OK        tinytex=0.52
OK        janitor=2.2.0
OK        gapminder=1.0.0
OK        readxl=1.4.3
OK        ottr=1.1.3
OK        canlang=0.0.1
OK        rmarkdown PDF-generation was successful.
OK        rmarkdown HTML-generation was successful.
```

![453175291_867619011380281_5813429940279746516_n](https://github.com/user-attachments/assets/dfe7340b-1af9-4dc0-b300-87ef8fd62ec1)

**Comment by joelostblom** [comment]
Thanks, very helpful!

1. Could you let me know the version you have installed for psql, rstudio, and docker for both Ubuntu and Windows?
2. For this version of Windows itself, PR https://github.com/UBC-MDS/UBC-MDS.github.io/pull/169 should fix it. Could you try running the script from that branch via `bash <(curl -Ss https://raw.githubusercontent.com/yuliaUU/UBC-MDS.github.io/yulia/resources_pages/check-setup-mds.sh)` and post the output related to the windows version?
3. For JupyterLab WebPDF, can you try running `playwright install chromium` as a separate command and then run the script again? What's the output from the playwright command?
4. For RMarkdown on Ubuntu, what's the output from running `Rscript -e "rmarkdown::find_pandoc(dir = c('/usr/lib/rstudio/resources/app/bin/quarto/bin/tools', 'C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools', '/Applications/RStudio.app/Contents/MacOS/quarto/bin/tools', '/Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools'), cache=F); rmarkdown::render('mds-knit-pdf-test.Rmd', output_format = 'pdf_document')"`? Could you find where `quarto` is installed on your system?

@chendaniely How much quarto vs Rmarkdown are you teaching in 521? Should we add any checks for quarto in the setup script (and maybe remove Rmarkdown at least next year)?

**Comment by andytai7** [comment]
1.

Windows versions:

Rstudio: 2024.04.2 build 764
PSQL: 16.3
Docker version: 27.0.3

Ubuntu versions: 

Rstudio: 2024.04.02 build 764
PSQL: 16.3
Docker 27.1.2, build d01f264

2. No changes in output:

```
## Operating system
Microsoft Windows 11 Pro
64-bit
10.0.22621

## System programs
MISSING   psql 15.*
MISSING   rstudio 2023.06*
OK        tlmgr revision 71331 (2024-05-24 09:30:36 +0200)
OK        R 4.4.1 (2024-06-14 ucrt) -- "Race for Your Life"
OK        python 3.12.3
OK        conda 4.7.1
OK        bash 4-pc-msys)
OK        git 2.46.0.windows.1
OK        make 4.4.1
OK        latex 3.141592653-2.6-1.40.26 (TeX Live 2024)
MISSING   docker=24.*
OK        code 1.91.1

## Python packages
OK        otter-grader=5.5.0
OK        pandas=2.2.2
OK        nbconvert-core=7.16.4
OK        playwright=1.45.1
OK        jupyterlab=4.2.4
OK        jupyterlab-git=0.50.1
OK        jupyterlab-spellchecker=0.8.4
OK        jupyterlab PDF-generation was successful.
MISSING   jupyterlab WebPDF-generation failed. It seems like you have not run playwright install chromium to download chromium for jupyterlab WebPDF export.
OK        jupyterlab HTML-generation was successful.

## R packages
OK        tidyverse=2.0.0
OK        markdown=1.13
OK        rmarkdown=2.27
OK        renv=1.0.7
OK        IRkernel=1.3.2
OK        tinytex=0.52
OK        janitor=2.2.0
OK        gapminder=1.0.0
OK        readxl=1.4.3
OK        ottr=1.1.3
OK        canlang=0.0.1
OK        rmarkdown PDF-generation was successful.
OK        rmarkdown HTML-generation was successful.

The above output has been saved to the file /c/Users/Admin/check-setup-mds.log
together with system configuration details and any detailed error messages about PDF and HTML generation.
You can open this folder in your file browser by typing explorer . (without the surrounding backticks).
Before sharing the log file, review that there is no SENSITIVE INFORMATION such as passwords or access tokens in it.

(base)
```

3. `playright install chromium` give me no output
Admin@DESKTOP-05S77UO MINGW64 ~
$ playwright install chromium

(base)
Admin@DESKTOP-05S77UO MINGW64 ~
$

4.

Output for this:
`"rmarkdown::find_pandoc(dir = c('/usr/lib/rstudio/resources/app/bin/quarto/bin/tools', 'C:/Program Files/RStudio/resources/app/bin/quarto/bin/tools', '/Applications/RStudio.app/Contents/MacOS/quarto/bin/tools', '/Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools'), cache=F); rmarkdown::render('mds-knit-pdf-test.Rmd', output_format = 'pdf_document')"`

gives me this:

$version
[1] ‘0’

$dir
NULL

Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
Execution halted

Quarto on my Ubuntu system is located 
quarto: /usr/local/bin/quarto /opt/quarto/bin/quarto

**Comment by joelostblom** [comment]
Thanks for the quick reply!

I put up a new PR that I think fixes 1,4 and maybe 3. Could you try running the following?

```
bash <(curl -Ss https://raw.githubusercontent.com/UBC-MDS/UBC-MDS.github.io/script-version-updates-2024-25/resources_pages/check-setup-mds.sh)
```

For 2, it looks to me like your output has changed as it no longer complains about an incompatible version of Windows, so I went ahead and merged Yulia's PR.

(PS when you post the output from your runs, you can enclose it in tripple backticks so that it is formatted as monospace output rather than markdown. I edited your post above, click the three dots and "edit" to see an example of what I mean.)

**Comment by andytai7** [comment]
Ouput of the new PR for Ubuntu:

```
# MDS setup check 2024.1

If a program or package is marked as MISSING,
this means that you are missing the required version of that program or package.
Either it is not installed at all or the wrong version is installed.
The required version is indicated with a number and an asterisk (*),
e.g. 4.* means that all versions starting with 4 are accepted (4.0.1, 4.2.5, etc).

You can run the following commands to find out which version
of a program or package is installed (if any):
name_of_program --version  # For system programs
conda list  # For Python packages
R -q -e "as.data.frame(installed.packages()[,3])"  # For R packages

Checking program and package versions...
pandoc 3.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/admin/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: [https://pandoc.org](https://l.facebook.com/l.php?u=https%3A%2F%2Fpandoc.org%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR3kEZCYWqrnh55TMTxZMkWjW8RNNSMZcO6PC_evC_k9dRiNxiydJ_I1lMQ_aem_nkFYPs4Y_VDS4PC-453vug&h=AT2gWmdSKNmtjGCNNPbCm3b3tLm2X_7pAUAaaGFAxy_QWdOkw_Xt_upDFEq9FuB8Hx2QmxgNH1ERcMsW4agJFTnI_zfM1PZAysUF-cHmcwQMeJSyJMWedchmG_H4Zu6f8gxSXmanBhV1PWCXbdU1RxAP)
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
pandoc 3.2
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/admin/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: [https://pandoc.org](https://l.facebook.com/l.php?u=https%3A%2F%2Fpandoc.org%2F%3Ffbclid%3DIwZXh0bgNhZW0CMTAAAR3kEZCYWqrnh55TMTxZMkWjW8RNNSMZcO6PC_evC_k9dRiNxiydJ_I1lMQ_aem_nkFYPs4Y_VDS4PC-453vug&h=AT2gWmdSKNmtjGCNNPbCm3b3tLm2X_7pAUAaaGFAxy_QWdOkw_Xt_upDFEq9FuB8Hx2QmxgNH1ERcMsW4agJFTnI_zfM1PZAysUF-cHmcwQMeJSyJMWedchmG_H4Zu6f8gxSXmanBhV1PWCXbdU1RxAP)
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

## Operating system
Operating System: Ubuntu 24.04 LTS
Architecture:     x86-64
Kernel:           Linux 6.8.0-39-generic

## System programs
MISSING   psql=14.*
MISSING   rstudio=2024.02.*
OK        R 4.4.1 (2024-06-14) -- "Race for Your Life"
OK        python 3.12.2
OK        conda 4.7.1
OK        bash 5.2.21(1)-release (x86_64-pc-linux-gnu)
OK        git 2.43.0
OK        make 4.3
OK        latex 3.141592653-2.6-1.40.26 (TeX Live 2024)
OK        tlmgr 5-24 09:30:36 +0200)
OK        docker 27.1.2, build d01f264
OK        code 1.92.1
OK        quarto 1.5.55

## Python packages
OK        otter-grader=5.5.0
OK        pandas=2.2.2
OK        nbconvert-core=7.16.4
OK        playwright=1.45.1
OK        jupyterlab=4.2.4
OK        jupyterlab-git=0.50.1
OK        jupyterlab-spellchecker=0.8.4
OK        jupyterlab PDF-generation was successful.
OK        jupyterlab WebPDF-generation was successful.
OK        jupyterlab HTML-generation was successful.

## R packages
OK        tidyverse=2.0.0
OK        markdown=1.13
OK        rmarkdown=2.27
OK        renv=1.0.7
OK        IRkernel=1.3.2
OK        tinytex=0.52
OK        janitor=2.2.0
OK        gapminder=1.0.0
OK        readxl=1.4.3
OK        ottr=1.1.3
OK        canlang=0.0.1
MISSING   rmarkdown PDF-generation failed. Check that quarto, latex, rmarkdown, and pandoc are marked OK above.
It seems that RMarkdown cannot find pandoc (should have been installed as part of quarto, check if  works)
MISSING   rmarkdown HTML-generation failed. Check that quarto, rmarkdown, and pandoc are marked OK above.
It seems that RMarkdown cannot find pandoc (should have been installed as part of quarto, check if  works)

The above output has been saved to the file /home/admin/check-setup-mds.log
together with system configuration details and any detailed error messages about PDF and HTML generation.
You can open this folder in your file browser by typing xdg-open . (without the surrounding backticks).
Before sharing the log file, review that there is no SENSITIVE INFORMATION such as passwords or access tokens in it.
```

And Windows output:

```# MDS setup check 2024.1

If a program or package is marked as MISSING,
this means that you are missing the required version of that program or package.
Either it is not installed at all or the wrong version is installed.
The required version is indicated with a number and an asterisk (*),
e.g. 4.* means that all versions starting with 4 are accepted (4.0.1, 4.2.5, etc).

You can run the following commands to find out which version
of a program or package is installed (if any):
name_of_program --version  # For system programs
conda list  # For Python packages
R -q -e "as.data.frame(installed.packages()[,3])"  # For R packages

Checking program and package versions...

## Operating system
Microsoft Windows 11 Pro
64-bit
10.0.22621

## System programs
OK        psql (PostgreSQL) 16.3
MISSING   rstudio 2024.02*
OK        tlmgr revision 71331 (2024-05-24 09:30:36 +0200)
OK        R 4.4.1 (2024-06-14 ucrt) -- "Race for Your Life"
OK        python 3.12.3
OK        conda 4.7.1
OK        bash 4-pc-msys)
OK        git 2.46.0.windows.1
OK        make 4.4.1
OK        latex 3.141592653-2.6-1.40.26 (TeX Live 2024)
OK        docker 27.0.3, build 7d4bcd8
OK        code 1.91.1
OK        quarto 1.5.55

## Python packages
OK        otter-grader=5.5.0
OK        pandas=2.2.2
OK        nbconvert-core=7.16.4
OK        playwright=1.45.1
OK        jupyterlab=4.2.4
OK        jupyterlab-git=0.50.1
OK        jupyterlab-spellchecker=0.8.4
OK        jupyterlab PDF-generation was successful.
OK        jupyterlab WebPDF-generation was successful.
OK        jupyterlab HTML-generation was successful.

## R packages
OK        tidyverse=2.0.0
OK        markdown=1.13
OK        rmarkdown=2.27
OK        renv=1.0.7
OK        IRkernel=1.3.2
OK        tinytex=0.52
OK        janitor=2.2.0
OK        gapminder=1.0.0
OK        readxl=1.4.3
OK        ottr=1.1.3
OK        canlang=0.0.1
MISSING   rmarkdown PDF-generation failed. Check that quarto, latex, rmarkdown, and pandoc are marked OK above.
MISSING   rmarkdown HTML-generation failed. Check that quarto, rmarkdown, and pandoc are marked OK above.

The above output has been saved to the file /c/Users/Admin/check-setup-mds.log
together with system configuration details and any detailed error messages about PDF and HTML generation.
You can open this folder in your file browser by typing explorer . (without the surrounding backticks).
Before sharing the log file, review that there is no SENSITIVE INFORMATION such as passwords or access tokens in it.
```

**Comment by joelostblom** [comment]
Great! It seems like that fixed the `playwright`/`webpdf` issue, which I was mostly concerned about might be time-consuming. I fixed a typo in the psql and rstudio checks, they should pass now too. I also fixed the quarto pandoc path as well as the occurences the printing of quarto version, so please run the script again from the same PR and see if all checks pass now on both OSes.

**Comment by andytai7** [comment]
For Windows and Ubuntu everything checks out except two line still seem to throw a missing output:  

```
MISSING   rmarkdown PDF-generation failed. Check that quarto, latex, rmarkdown, and pandoc are marked OK above.
MISSING   rmarkdown HTML-generation failed. Check that quarto, rmarkdown, and pandoc are marked OK above.
```

**Comment by joelostblom** [comment]
Just double checking, is that the new output or did you copy from above for convenience? I [changed the line with the error message to not include "pandoc"](https://github.com/UBC-MDS/UBC-MDS.github.io/pull/220/files#diff-a10c06bd7270b5952b9c542f6981913e9e468e2d6a1cf7a3c0400713d65cef5dR297), so just want to make sure you ran it from the PR.

If it is from the new PR, could you check the output of: 

```
touch mds-knit-pdf-test.Rmd
Rscript -e "rmarkdown::render('mds-knit-pdf-test.Rmd', output_format = 'pdf_document')"
Rscript -e "rmarkdown::render('mds-knit-pdf-test.Rmd', output_format = 'html_document')"
```

**Comment by andytai7** [comment]
For Ubuntu there was a different output, the updated output was 

```
MISSING   rmarkdown PDF-generation failed. Check that quarto, rmarkdown, and latex are marked OK above.
MISSING   rmarkdown HTML-generation failed. Check that quarto and rmarkdown are marked OK above.
```

**Comment by joelostblom** [comment]
Ok that makes sense. Could you run the commands above so that we get to see the error and we can troubleshoot from there?

**Comment by andytai7** [comment]
For Ubuntu i am getting 

```
(base) admin@stty2u-ThinkPad-X1-Carbon-5th ~
$ touch mds-knit-pdf-test.Rmd
Rscript -e "rmarkdown::render('mds-knit-pdf-test.Rmd', output_format = 'pdf_document')"
Rscript -e "rmarkdown::render('mds-knit-pdf-test.Rmd', output_format = 'html_document')"
Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
Execution halted
Error: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).
Execution halted
```

Should i run it for windows as well?

**Comment by joelostblom** [comment]
Oh interesting, I think rmarkdown cannot find that path where quarto has installed pandoc. That's unexpected since they are both from RStudio, but maybe we can specify it manually then. I will have a look.

No need to run on windows since the checks were note failing there

**Comment by andytai7** [comment]
@joelostblom 

just to be clear i am still getting these errors on window:

```
MISSING   rmarkdown PDF-generation failed. Check that quarto, rmarkdown, and latex are marked OK above.
MISSING   rmarkdown HTML-generation failed. Check that quarto and rmarkdown are marked OK above.
```

**Comment by joelostblom** [comment]
Ah ok, try again now on both ubuntu and windows

**Comment by andytai7** [comment]
Nice everything looks good on my end!

**Comment by joelostblom** [comment]
:tada:
