### ISSUE TITLE
Website links that need fixing

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#30]
On the navigation menu at the top of the page, the "Resources" & "Official Website" take you somewhere that makes sense, but the "Program" and "Capstone" links do not (only their sub-links do). These should be fixed to send folks to the closest thing to a landing page for these topics.

**Comment by joelostblom** [comment]
I think this is intuitive as it looks currently as the little down arrow on Program and Capstone indicates that there will be a sub-menu coming out of them:

![image](https://user-images.githubusercontent.com/4560057/90166445-1dc7a700-dd4f-11ea-8a97-888f15e774fa.png)

If you prefer, I can add a link to the about page for the Capstone nav heading, and either the about page or the official program page for the Program nav heading.

**Comment by joelostblom** [comment]
@ttimbers Do you think we can close this or would you like there to be a landing page for those header links?

**Comment by ttimbers** [comment]
I think I may have missed the down arrow? Either way, it's perhaps not a good use of our time (there are more urgent or important issues that need attention).
