### ISSUE TITLE
Where to download git from

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#36]
@Lourenzutti - FYI in the mac OS install instructions we tell them to install Git via `xcode-select --install`, on my laptop this leads to an older version of Git being installed than what you can install from https://sourceforge.net/projects/git-osx-installer/ . Typically this would not be an issue, however there were some new cool commands (related to checking out old versions) added to Git this last release, and if you were planning on teaching them this year you might want to get people to ugrade their Git.

**Comment by Lourenzutti** [comment]
@ttimbers - I can update the instruction. 

Is the installation process using the file from sourceforge self-explanatory? I could ask them to "Download the latest version [here](https://sourceforge.net/projects/git-osx-installer/), and follow the instructions".

**Comment by ttimbers** [comment]
OK, I did a bit more reading. The new commands ([git switch & restore](https://www.infoq.com/news/2019/08/git-2-23-switch-restore/)) look cool, but I think we're probably not yet ready to teach them this month, and it seems that at least for Mac to get that version of Git you would have to install from source (which is not as simple as downloading things).

Thus, let's leave things as they are this year, but for next year I can imagine we want to teach these commands and make sure students have a recent enough version of Git to use them. Could you please open an issue in the DSCI 521 repo about this and then close this one once you have done that? Thanks!

**Comment by jennybc** [comment]
I think they could get bleeding edge Git if they installed via homebrew, which is a good thing for the macOS people to know about anyway.

**Comment by ttimbers** [comment]
ooh! That's good to know, I will test it out. @Lourenzutti - what's the version installed on Windows and Linux with the instructions you have provided so far? It's version 2.23 and higher that will have these two new commands.

**Comment by Lourenzutti** [comment]
It is the latest version 2.23, on both, Windows and Linux.

**Comment by ttimbers** [comment]
I can confirm now that installing Git through homebrew does in fact install Git 2.23. I will update our install instructions to suggest people do that.

**Comment by ttimbers** [comment]
`xcode-select --install` now installs a high enough version of Git so I have switched back to this now (so they are not required to install homebrew).
