### ISSUE TITLE
Install instructions update for Mac needed

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#38]
We should tell people using Macs to install XQuartz. Some rare R packages depend on it... https://www.xquartz.org/

**Comment by ttimbers** [comment]
I'm having second thoughts about this one... I will consult with Jenny.

**Comment by ttimbers** [comment]
It seems we should from here: https://www.r-bloggers.com/installing-r-on-os-x/

**Comment by ttimbers** [comment]
And Jenny confirms this, I have added it.

**Comment by jennybc** [comment]
From the official installation instructions for R for macOS:

https://cran.r-project.org/bin/macosx/

> R 4.0.0 binary for macOS 10.13 (High Sierra) and higher, signed and notarized package. Contains R 4.0.0 framework, R.app GUI 1.71 in 64-bit for Intel Macs, Tcl/Tk 8.6.6 X11 libraries and Texinfo 6.7. The latter two components are optional and can be ommitted when choosing "custom install", they are only needed if you want to use the tcltk R package or build package documentation from sources.
>
> **Note: the use of X11 (including tcltk) requires XQuartz to be installed since it is no longer part of OS X. Always re-install XQuartz when upgrading your macOS to a new major version.**

It sounds like one could attempt an XQuartz-free life, but I never have and I suspect it would create more problems than it solves.

**Comment by ttimbers** [comment]
So it comes with the R 4.0.0 binary for macOS now? So we don't need to separately install it? But with the caveat that if you upgrade your OS you need to update XQuartz (but not necessarily R)?

**Comment by jennybc** [comment]
I have always interpreted this as YOU need to install XQuartz. And furthermore, reinstall it when you upgrade your OS.

**Comment by ttimbers** [comment]
Thanks for the clarification, it is much appreciated. This is what I now have in the install instructions.
