### ISSUE TITLE
Install TinyTeX next year instead of MacTeX & MikTeX

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#40]
I have run into some major issues rendering Rmd to pdf using MacTeX, and colleagues have reported similar problems using MikTeX on Windows. Both of these issues were solved by unistalling MacTeX or MikTeX and installing [TinyTeX](ubc.ca1.qualtrics.com/Q/MyProjectsSection). Thus, I suggest we explore whether TinyTeX will support what we need for LaTeX in Jupyter notebooks, and if so, use that going forward.

**Comment by ttimbers** [comment]
Updated for mac (on incoming PR). Still need to do for Mac and Linux.

**Comment by ttimbers** [comment]
Added for Mac and Linux, need to add for Windows. 

However, we still need to add a note that if they have previously installed TexLive, they will first need uninstall this for it to work.

**Comment by ttimbers** [comment]
cc @joelostblom

**Comment by joelostblom** [comment]
Closed by #66 #61
