### ISSUE TITLE
Hamburger menu doesn't render on mobile

### ISSUE THREAD

**Issue by jennybc** [UBC-MDS/UBC-MDS.github.io-jekyll#5]
On my way to class today I tried to visit the site on my phone. So I could navigate to the calendar and look up which room I teach in on Mondays. From a phone the "hamburger menu" doesn't work.

**Comment by mgelbart** [comment]
The navigation works fine on my iPhone 5 running iOS 10. Perhaps you haven't updated your phone lately... just a guess? ;)

**Comment by jennybc** [comment]
I have the new iOS! Of course, now that I am home and on fibre-supplied wireless it works. I wonder if this was an issue of crappy/slow cellular data? I'll close. Someone can reopen if we have other reports of problems.
