### ISSUE TITLE
Test if Firefox works with canvas latex and uploaded images

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/UBC-MDS.github.io-jekyll#58]

**Comment by joelostblom** [comment]
I have tested Firefox with syzygy and it seems to be working fine (this is what I used for my presentation on jupyterdaysand it is listed in the recommended syzygy browsers).

I just tested with canvas quizzes (latex and uploaded image on both the classic and new quiz) and this is what it looks like (they don't have the exact same options). I did not notice any differences between Firefox and Chrome so if the below look good to you @ttimbers and @mgelbart I will add Firefox to the installation instructions.

# "Classic" Canvas quiz

Quiz description:
![image](https://user-images.githubusercontent.com/4560057/90173149-dd6d2680-dd58-11ea-9787-2bd835a27983.png)

Quiz questions:
![image](https://user-images.githubusercontent.com/4560057/90173226-fbd32200-dd58-11ea-9b20-22e92ee0903d.png)


# "New" Canvas  quiz

Quiz description and questions:
![image](https://user-images.githubusercontent.com/4560057/90173945-0f32bd00-dd5a-11ea-9600-b5bf44e9cf8b.png)

**Comment by ttimbers** [comment]
Sounds good, I support this!
