### ISSUE TITLE
flake8 Jupyter Lab extension

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#69]
@TomasBeuzen - the flake8 Jupyter Lab extension looks more useful than the command line tool fro 511... Do you think you might want to use this? If so, please let us know so that we can add it to the install instructions:

- [flake8 Jupyter Lab extension](https://github.com/mlshapiro/jupyterlab-flake8)

cc @joelostblom @hfboyce

**Comment by joelostblom** [comment]
I actually wanted to use this myself previously, but I ran into this issue https://github.com/mlshapiro/jupyterlab-flake8/issues/37, which prevented me from testing it out. I haven't followed up on it for a while, but seems like several people are sharing the problem (a solution is suggested in the comments also).

**Comment by TomasBeuzen** [comment]
Haven't used this extension myself - one of my colleagues told me it really slowed down their notebooks. I see @joelostblom [posted an issue](https://github.com/mlshapiro/jupyterlab-flake8/issues/37) about it not working recently too? I might just reference to it as an option but I don't think I want to use it/make it a course dependency...

I am showing the [Jupyter Lab Code Formatter](https://jupyterlab-code-formatter.readthedocs.io/en/latest/installation.html) in lectures at the moment though and we could add that to the install instructions.

**Comment by ttimbers** [comment]
If you are going to use this @TomasBeuzen (or any other software) in block 1, you need to tell us so we can add to the install instructions.

**Comment by ttimbers** [comment]
OK @hfboyce & @mgelbart - based on the conversation above, perhaps we don't want to use this Jupyter Lab extension for the MDS MCL prog course?

**Comment by mgelbart** [comment]
I'm happy with whatever you two decide!

**Comment by hfboyce** [comment]
Ok That's fine with me!

**Comment by joelostblom** [comment]
It seems like we didn't need this last year so closing. Please reopen if needed @ttimbers
