### ISSUE TITLE
Consider recommending other Windows terminal emulators than mintty

### ISSUE THREAD

**Issue by joelostblom** [UBC-MDS/UBC-MDS.github.io-jekyll#70]
@ttimbers wrote:

>     * [ ]  Under "Essential Python packages", or before in the configuring Git Bash section, can we add instructions on how to copy and paste into Git Bash (Ctrl + V doesn't work, you need to right click and select paste).

Yes, thanks for pointing this out, I forgot to add this in. I actually wanted to open an issue about a larger semi-problem here. The mintty terminal emulator that comes with git bash is not great, partly because of some of the strange keyboard shortcuts, but also lack of configuration, the fact that you can't run some interactive programs such as `python` without flags, and I have also have problems a few years ago with python scripts that print to terminal that do not work correctly (not all characters are printed).

In my experience, [con emu](https://conemu.github.io/), is a more reliable and configurable emulator. It will run git bash as its default shell if installed after git bash, so there is very little setup required. However, it looks a little intimidating maybe since it has more options and buttons, and the default colors are a little worse. A nice default setup of con emu is provided via [cmder](https://cmder.net/) which also packs some extra tools for windows users via [clink](https://mridgers.github.io/clink/), however, it is only provided as a binary, not an installable program. 

I opted for using Git Bash as the default, since I did not want to change too much. We could mention con emu as an optional install for people who are interested in tinkering with it (since it runs the git bash shell inside, there should not be any differences), but the safer option right now might be to not say anything but have it as a backup if Git bash would choke at some specific task (but I guess it hasn't in previous years?) . One concern I have with this is that the default Git Bash terminal experience in Windows is a bit lackluster and might put students off from using the terminal, whereas con emu has been really great when I have used it in the past. What do you think about this?

Note that this will still be relevant is we switch from Git Bash to WSL(2) in the future, since WSL also needs to run in a terminal emulator. Another alternative to mintty is https://github.com/alacritty/alacritty, but it is still in beta, there is also hyper.js but I don't have much experience with it.

**Comment by joelostblom** [comment]
@ttimbers I am torn between potentially increasing our support burden (although probably not) with suggesting a terminal emulator we did not use last year, and exposing Windows users to a bad terminal experience just because the mintty emulator that ships with Git Bash is not that intuitive, whereas ConEmu behaves like one would expect.

I don't think ConEmu fails in any areas where mintty succeeds, but there has been a few years since I used it regularly, so I can't say for certain that there aren't any oddities with it (to be clear, it is not some obscure software, e.g. it is [voted as the most popular windows terminal emulator](https://alternativeto.net/software/windows-command-prompt-cmd/) with almost 9 times the number of votes that mintty has).

Although ConEmu would require one additional step in the installation instructions, it would also remove ~three~ two current "note" sections that we have to explain peculiarities of GitBash (~`python -i`~, `Ctrl-V`, pinning directly from the taskbar). So I don't think the overall complexity of the instructions increases (and arguably the cognitive load of the students would decrease because they don't have to remember that their terminal behaves differently from all other programs).

The installation section could look something like this:

> We're going to use a more powerful terminal than the default one for Git Bash, called [ConEmu  which you can download and install from here](https://github.com/Maximus5/ConEmu/releases/download/v20.07.13/ConEmuSetup.200713.exe). In the settings window that appears the first time you launch ConEmu, make sure to select `{Bash::Git bash}` as your "startup task"  (where it says `{Shells::Cmd}` by default). This is the only configuration option that you *need* to change, but you are free to change the appearance settings as you wish.

**Comment by ttimbers** [comment]
If you want to do this, you need to test out the downstream implications. Specifically the following:

1. Running R & Python scripts 
2. Running Make pipelines
3. Running docker, in particular mounting volumes, and running bash and make scripts non-interactively (for example - can you run this project: https://github.com/ttimbers/breast_cancer_predictor

Number 3 listed above is the most problematic and inconsistent across shells and OS's. We need to know how that (and if it will) work before we change things.

**Comment by ttimbers** [comment]
Also, try running this: `docker run --rm -v /$(pwd):/home/rstudio/breast_cancer_predictor ttimbers/bc_predictor:v4.0 /bin/bash` to enter that container non-interactively.

**Comment by joelostblom** [comment]
> Also, try running this: docker run --rm -v /$(pwd):/home/rstudio/breast_cancer_predictor ttimbers/bc_predictor:v4.0 /bin/bash to enter that container non-interactively.

I am trying this in Git Bash first so that I know what to expect. After pulling down the image, I see an error "no such file or directory", this seems to be windows path related and when I switch `/bin/bash` for `//bin/bash` it runs without error. However, I get no output, is this what is expected?

(Also I was wrong about `python -i` this is still the same in ConEmu since it is running the exact same shell as Git Bash) (which also means there should not be any differences in running scripts etc, just the UI and the two things I noted above)

**Comment by joelostblom** [comment]
I have been thinking more about this and suggest that we do not go down the ConEmu route this year. The [main reason is this note from the developer](https://conemu.github.io/en/CygwinAnsi.html) on potential problems with msys based she compatibility layers. I have not run into any myself, but since it is noted in the docs that these tools sometimes relies on the hacky behavior in pseudo-emulators such as mintty, it seems unnecessary to take the risk. 

Another reason is that WSL2 is supposed to be installed by default in newer versions of Windows, it will be able to run GUI applications, and MS [finally are developing what seems to be a decent terminal emulator](https://devblogs.microsoft.com/commandline/introducing-windows-terminal/) (which will be compatible with Ubuntu via WSL). Using WSL2 would bring us real bash which would also fix issues with using msys (I tried both via Git Bash, msys2, and cygwin and they all have their peculiarities).

We might be able to get this up and running this year, but given the time we have already put into refining the Git Bash instructions, and the fact that these tools are pretty new, I think it is wise to give this another year to mature and try switching next year. 

If you agree please close this, I'll open a new issue as reminder.
