### ISSUE TITLE
Add TOC link to Post-installation notes

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#76]
@joelostblom - can you please add a TOC link to Post-installation notes? I think we (and the students) will find that very helpful!

**Comment by ttimbers** [comment]
Also, can you show a sample successful output from the script so students know what to expect?

**Comment by joelostblom** [comment]
Great idea! I will add this later in the afternoon as a separate PR.

**Comment by ttimbers** [comment]
Sounds good - you can merge #79 once you fix the conflicts then.
