### ISSUE TITLE
Add instructions to add R assignment symbol and pipe to Jupyter lab

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/UBC-MDS.github.io-jekyll#84]
@joelostblom - I forgot this was an issue last year. One student documented a way to deal with this here: https://github.com/ryanhomer/jupyterext-text-shortcuts

**Comment by ttimbers** [comment]
Ah, I forget to add my ask above, can we please add this to the install instructions our students follow. Thanks!

**Comment by joelostblom** [comment]
@ttimbers  I like your suggestion to add default shortcuts in https://github.com/ryanhomer/jupyterext-text-shortcuts/issues/3. This would make the setup easier and minimize error from students pasting into the JSON settings (which might also be a bit confusing for novices).

Should I wait for you to contribute that feature? Or do you think it might take a while before you get there? Or could we ask if the author is willing to make this the default behavior of the plugin even if it is not language specific as these key combos are not bound to anything currently?

**Comment by ttimbers** [comment]
It's going to take me a while. We should just add as is for now as it works...

**Comment by ttimbers** [comment]
Unless you have time to step in here?

**Comment by joelostblom** [comment]
Ok I will add it as is in a PR later tonight or tomorrow. I am not very familiar with JL extensions, so it would take me some time too unfortunately.

**Comment by ttimbers** [comment]
Looks like he is going to work on it this week, and has made progress on the kernel specificity. Let's hold on and wait on you contributing as its outside your wheelhouse. We can add this in later (meaning we still should ship the instructions this week), even if its an improvement to the install that we update later. At a minimum let's add it as is for now.

**Comment by ttimbers** [comment]
I just updated the comment above.

**Comment by joelostblom** [comment]
Sounds good, I will send the instructions as is to the test students tomorrow morning. And then when we here back from Ryan we can add either his original instructions or the updated plugin if he gets it to work.

**Comment by ttimbers** [comment]
Oh, I think we should include the original instructions, as they currently work.
